language: go

sudo: false

go:
  - 1.9.x
  - 1.10.x

before_install:
  - go get github.com/golang/lint/golint

before_script:
  - go vet ./...
  - golint ./...

script:
  - go test -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token
